commands = [
    ("Выключить телевизор", "ssap://system/turnOff", {}),
    ("Открыть браузер по URL", "ssap://system.launcher/open", {"target": "https://example.com"}),
    ("Показать уведомление", "ssap://system.notifications/createToast", {"message": "Сообщение"}),
    ("Показать предупреждение", "ssap://system.notifications/createAlert", {"message": "Сообщение", "buttons": [{"label": "ОК"}]}),
    ("Закрыть предупреждение", "ssap://system.notifications/closeAlert", {"alertId": "123"}),
    ("Установить громкость", "ssap://audio/setVolume", {"volume": 15}),
    ("Включить/выключить звук", "ssap://audio/setMute", {"mute": True}),
    ("Получить статус звука", "ssap://audio/getStatus", {}),
    ("Получить текущую громкость", "ssap://audio/getVolume", {}),
    ("Увеличить громкость", "ssap://audio/volumeUp", {}),
    ("Уменьшить громкость", "ssap://audio/volumeDown", {}),
    ("Воспроизведение", "ssap://media.controls/play", {}),
    ("Остановить", "ssap://media.controls/stop", {}),
    ("Пауза", "ssap://media.controls/pause", {}),
    ("Перемотка назад", "ssap://media.controls/rewind", {}),
    ("Перемотка вперёд", "ssap://media.controls/fastForward", {}),
    ("Канал вверх", "ssap://tv/channelUp", {}),
    ("Канал вниз", "ssap://tv/channelDown", {}),
    ("Установить канал", "ssap://tv/openChannel", {"channelId": "1"}),
    ("Текущий канал", "ssap://tv/getCurrentChannel", {}),
    ("Список каналов", "ssap://tv/getChannelList", {}),
    ("Получить socket курсора", "ssap://com.webos.service.networkinput/getPointerInputSocket", {}),
    ("Отправить Enter", "ssap://com.webos.service.ime/sendEnterKey", {}),
    ("Включить 3D", "ssap://com.webos.service.tv.display/set3DOn", {}),
    ("Выключить 3D", "ssap://com.webos.service.tv.display/set3DOff", {}),
    ("Список входов", "ssap://tv/getExternalInputList", {}),
    ("Переключить вход", "ssap://tv/switchInput", {"inputId": "HDMI_1"}),
    ("Информация о ПО", "ssap://com.webos.service.update/getCurrentSWInformation", {}),
    ("Список сервисов", "ssap://api/getServiceList", {}),
    ("Список приложений (Launcher)", "ssap://com.webos.applicationManager/listLaunchPoints", {}),
    ("Запуск приложения с payload", "ssap://com.webos.applicationManager/launch", {"id": "app.id"}),
    ("Запустить приложение", "ssap://system.launcher/launch", {"id": "app.id"}),
    ("Закрыть приложение", "ssap://system.launcher/close", {"id": "app.id"}),
    ("Открыть YouTube по ID", "ssap://system.launcher/launch", {"id": "youtube.leanback.v4", "params": {"contentTarget": "http://www.youtube.com/tv?v=videoid"}}),
    ("Открыть YouTube по URL", "ssap://system.launcher/launch", {"id": "youtube.leanback.v4", "params": {"contentTarget": "http://youtube.com"}}),
    ("Информация о текущем приложении", "ssap://com.webos.applicationManager/getForegroundAppInfo", {}),
    ("Состояние питания", "ssap://com.webos.service.tvpower/power/getPowerState", {}),
    ("Аудио выход", "ssap://com.webos.service.apiadapter/audio/getSoundOutput", {}),
    ("Информация о системе", "ssap://system/getSystemInfo", {}),
    ("Список приложений", "ssap://com.webos.applicationManager/listApps", {}),
    ("Установить аудиовыход", "ssap://audio/changeSoundOutput", {"output": "external_speaker"}),
    ("Выключить экран", "ssap://com.webos.service.tvpower/power/turnOffScreen", {"standbyMode": "active"}),
    ("Включить экран", "ssap://com.webos.service.tvpower/power/turnOnScreen", {"standbyMode": "active"}),
    ("Настройки изображения", "ssap://settings/getSystemSettings", {"category": "picture", "keys": ["contrast", "backlight", "brightness", "color"]}),
    ("Ввести текст", "ssap://com.webos.service.ime/insertText", {"text": "текст"})
]